version: '3.1'
services:
  web:
      build: .
      ports:
          - "8090:80"
      volumes:
        - .:/var/www/html
      env_file:
        - .env
        - dev.env
  mysql:
      image: mysql:5
      restart: always
      environment:
          - MYSQL_HOST=localhost
          - MYSQL_DATABASE=db
          - MYSQL_ROOT_PASSWORD=pw
          - MYSQL_USER=lesempolem
          - MYSQL_PASSWORD=pw
      volumes:
          - "./data/db/mysql:/var/lib/mysql"
      ports:
        - "3320:3306"
  adminer:
      image: adminer:latest
      ports:
        - "88:8080"