# Registration form for running competition called Lesempolem
# For more information please visit https://lesempolem.cz
- name: lesempolem
  api:
    client: "*"               # used for CORS
    bearer: ""                # no password when empty or missing
    limits:
      list: "0"               # unlimited
      get: "-1"               # not used - disabled
      put: "10m"              # 10 req / minute
      delete: "-1"            # not used - disabled
  fields:
    firstname:
      type: "string"
      required: true
      min: 1
      max: 200
    lastname:
      type: "string"
      required: true
      min: 1
      max: 200
    email:
      type: "string"
      required: true
      rule: "email"
      min: 4
      max: 200
    club:
      type: "string"
      max: 200
    born:
      type: "date"
      required: true
      format: "2006/01/02"
    gender:
      type: "string"
      required: true
      min: 1
      max: 1
    race:
      type: "string"
      required: true
      min: 1
